### ISSUE TITLE
Utilisation du serveur du groupe R4

### ISSUE THREAD

**Issue by AmalBACHARA** [AmalBACHARA/VT-Planning#1]
essayer de récupérer le serveur afin de faire le lien avec la consultation.

Après cela, il faut commencer à faire les différentes requête ajax pour l'affichage des données.
Ne pas oublier de faire la modification dans les différents scripts.

**Comment by AmalBACHARA** [comment]
Nous avons pu récupérer le serveur ainsi que la base de données 
Diarra a commencé à réaliser des tests sur cette base

Adrien et moi-même avons commencé à rechercher comment ajouter les informations de la base dans le calendrier.

**Comment by AmalBACHARA** [comment]
Nous n'utiliserons pas le serveur du projet R4 pour l'utilisation de la base de données. Car ce serveur génère 4 tables : Enseignement, matière filière et enseignant qui ne nous permet pas d'afficher toutes les données nécessaires pour notre consultation. 
En utilisant cette base simplifiée générée par le groupe R4, plusieurs interfaces et fonctionnalités de notre application ne seront plus accessibles.
En gros, notre application servira juste de consultation de l'emploi du temps sans plus.

Mais nous nous baserons sur l'ancienne base de données délivrée par M COURTAUD.

**Comment by DiarraDIOP** [comment]
On a été confronté à l'utilisation de Nodejs et des requêtes SQL depuis un bon bout de temps. 
Finalement, cela ne nous servira plus. Après un entretien avec le prof, nous allons repartir de la base de début.
